### ISSUE TITLE
Cannot find name '_Service'  when _service in Query

### ISSUE THREAD

**Issue by liyin** [babyfish-ct/graph-state#2]
当服务端的Query  里面有{ _service: _Service}的时候，用框架生成客户端代码，运行yarn start 会报Cannot find name '_Service'  的错误。请问咋子处理？

ERROR in src/__generated/fetchers/QueryFetcher.ts:177:25

TS2304: Cannot find name '_Service'.
    175 |         readonly id: string
    176 |     }>;
    177 |     readonly _service?: _Service;
           |                                   ^^^^^^^^
    178 | }

**Comment by babyfish-ct** [comment]
在代码生成器中使用excludedTypes试试。

详情请参见https://github.com/babyfish-ct/graphql-ts-client/blob/master/doc/generator_zh_CN.md

**Comment by liyin** [comment]
按文档写了排除指令，还是生成了——在QueryFetcher.ts 里：export interface QueryFlatType {readonly _service?: _Service;}

const {GraphQLStateGenerator, loadRemoteSchema} = require("graphql-ts-client-codegen");
const path = require("path");
const generator = new GraphQLStateGenerator({
    schemaLoader: async() => {
        return loadRemoteSchema("http://localhost:8071/graphql");
    },
    excludedTypes : ["_Servcie"],
    targetDir: path.join(__dirname, "../src/__generated")
});
generator.generate();

**Comment by liyin** [comment]
按文档写了排除指令，还是生成了——在QueryFetcher.ts 里：export interface QueryFlatType {readonly _service?: _Service;}

const {GraphQLStateGenerator, loadRemoteSchema} = require("graphql-ts-client-codegen");
const path = require("path");
const generator = new GraphQLStateGenerator({
    schemaLoader: async() => {
        return loadRemoteSchema("http://localhost:8071/graphql");
    },
    excludedTypes : ["_Servcie"],
    targetDir: path.join(__dirname, "../src/__generated")
});
generator.generate();

**Comment by babyfish-ct** [comment]
请尝试3.1.10

我已经模拟你的情况测试，如果在你的场景中也解决了问题，请关闭此issue，祝后续开发过程愉悦

**Comment by liyin** [comment]
感谢！现在可以从excludedTypes排队了。我想是因为框架不支持"_" 打头的。
