### ISSUE TITLE
Error when fetching same query more than once with different id

### ISSUE THREAD

**Issue by robsonfj** [babyfish-ct/graph-state#4]
Getting this error when two or more queries to get User are executed
```
Uncaught (in promise) Error: Cannot find the associaton field 'Query.user:{"id":"1s92097ie9xn91drqrnsbwg37j"}' for object whose id is '____QUERY_OBJECT____'
    at cs.graph (QueryService.js:40:27)
    at cs.query (QueryService.js:22:25)
    at cs.<anonymous> (QueryService.js:136:37)
    at Generator.next (<anonymous>)
    at n (QueryService.js:5:58)
```

This is an example of what i'm tring to do.
The component UserInfo is loaded for each user off the userMetadata list (witch has less info and is faster to load), and every UserInfo has the button to Show more information on the user, so every user i click to show more makes a query to fetch a more complete data on the user,  but when i do that to more than 1 user i get the error above.  Am i doing something wrong? or is really a bug?
```
export const UserInfo = memo(({ loading, userMeta, showMore, onShowMore }: Props) => (
  <Column gap={1.6} padding={'1rem'}>
    <Field loading={loading} title={'ID'} value={userMeta.id} />
    <Field loading={loading} title={Tr('full_name')} value={`${userMeta.name} ${userMeta.lastName}`} />
    {!showMore && <x.a onClick={() => onShowMore?.(userMeta.id)}>More</x.a>}
    {showMore && <MoreInfo id={userMeta.id} />}
  </Column>
))

const MoreInfo = ({ id }: { id: string }) => {
  const { data, loading: loadingMore } = useQuery(query$.user(userFetcher), {
    id,
  })

  const more = data?.adminUserByID

  return (
    <>
    <Field loading={loadingMore} title={'Email'} value={more.mail} />
    <Field loading={loadingMore} title={'Email Confirmed'} value={String(more.confirmationStatus || false)} />
      <Field loading={loadingMore} title={Tr('phone')} value={more?.phone} />
      <Field
        loading={loadingMore}
        title={Tr('created_in')}
        value={more?.createdAt && new Date(more.createdAt).toLocaleDateString()}
      />
      <Field
        loading={loadingMore}
        title={Tr('updated_at')}
        value={more?.updatedAt && new Date(more.updatedAt).toLocaleDateString()}
      />
    </>
  )
}
```

**Comment by babyfish-ct** [comment]
Can you paste the raw response from your browser?

Possible reason: Client library except an empty array `[]` for collection association, but server-side returns null/undefined.
(When graphql-state is designed, Null/undefined is not supported for list association)

**Comment by robsonfj** [comment]
Here the  query and response for the first request that was OK
```
Query: {
  "query": "query(
	$id: ID!, 
	$first: Int, 
	$cursor: ID
) {
	user(id: $id) {
		id
		createdAt
		updatedAt
		phone
		workspaces(first: $first, cursor: $cursor) {
			id
			name
		}
	}
}
",
  "variables": {
    "id": "1u7hxyy1dura92c2rfxdgfekvz"
  }
}

Response: {
    "data": {
        "user": {
            "id": "1u7hxyy1dura92c2rfxdgfekvz",
            "createdAt": "2022-08-08T17:18:16.433Z",
            "updatedAt": "2022-08-08T19:03:19.505Z",
            "phone": "+5532972648554",
            "workspaces": [
                {
                    "id": "260ddzpa6rpwt000hy2i8qs4lb",
                    "name": "My workspace"
                }
            ]
        }
    }
}
```

Here the second request query and response that triggered the Error
```
Query: {
  "query": "query(
	$id: ID!, 
	$first: Int, 
	$cursor: ID
) {
	user(id: $id) {
		id
		createdAt
		updatedAt
		phone
		workspaces(first: $first, cursor: $cursor) {
			id
			name
		}
	}
}"
,
  "variables": {
    "id": "1s92097ie9xn91drqrnsbwg37j"
  }
}

Response: {
    "data": {
        "user": {
            "id": "1s92097ie9xn91drqrnsbwg37j",
            "createdAt": "2022-08-08T16:58:26.104Z",
            "updatedAt": "2022-08-08T17:13:07.023Z",
            "phone": "+55615789975456",
            "workspaces": [
                {
                    "id": "1ubvde1ckvkmn1cbgwqndadfzz",
                    "name": "My workspace"
                }
            ]
        }
    }
}
```

**Comment by babyfish-ct** [comment]
0.0.35 can resolve your problem.

-------------------------------------------

The original bug is fixed, but you will met a new problem(not bug), I'll describe it and tell you how to resolve it.

1. Get the simple rows of [parent-1, parent-2], without childNodes.

2. Get the details of `parent-1`: { name: "parent-1", childNodes: [child-1, child-2]}

3. Get the details of `parent-2`: { name: "parent-2", childNodes: [child-3, child-4]}

    After this step, the details of `parent-1` will be refreshed automatically, because: 
    
    `child-3` and `child-4` are inserted into the embedded database of graphql-state when the details of `parent-2` is fetched. However, the details of `parent-1` also contains the association `Parent.childNodes`, so graphql-state does not know whether these insert operations of child-3 and child-4 can can affect the details of `parent-1`
    
How to resolve it?

   The query body with problem look like this
   ```
   query$.parent(
       parentNode$$
       .childNodes(
           childNode$$
       )
   )
   ```
   
   Now, please
   1. Configure two-way association, it is combined by `ParentNode.childNodes` and `ChildNode.parentNode`, documentation link: https://github.com/babyfish-ct/graphql-state/blob/master/doc/graph-state/mutation/bidirectional-association.md
   
   2. Change query body to
       ```
       query$.parent(
          parentNode$$
           .childNodes(
               childNode$$
               .parentNode(parentNode$.id) // back ref property with only id
           )
       )
       ```
   The new code fetches childNodes, it also fetch parentId for each childNode.
   
   By this way, graphql-state knows that `child-3` and `child-4` only have associations with details `parent-2`, the details of `parent-1` will NOT be affected, absolutely!

**Comment by robsonfj** [comment]
Thanks, the issue is fixed.
Indeed the new problem ocurred, i will apply the suggested changes to resolve it, thanks
