### ISSUE TITLE
Cached data not being updated

### ISSUE THREAD

**Issue by robsonfj** [babyfish-ct/graph-state#5]
I'm currently having an issue with graphl state cache.

Say i have created this query in a component to fetch user name and lastname:
`useQuery(query$.user(user$.id.name.lastname))`

later in the components children i want to obtain the same user with same ID, but with a little bit more information:
`useQuery(query$.user(user$.id.name.lastname.phone.city.state))`

The graphql state only looks at the cached data, and it never does another query to obtain the missing data....

**Comment by babyfish-ct** [comment]
Yes, I reproduced this problem.

For lonely object without any associations, different shape with only scalar properties will be considered as same one.

I will fix it.

**Comment by babyfish-ct** [comment]
Hi robsonfj, please try 0.3.6.

Please close it after your validation

**Comment by robsonfj** [comment]
This fix is throwing errors for optional scalars 
`Uncaught (in promise) Error: Cannot find the scalar field 'phone:undefined' for object whose id is '0wmciuwpd854g2uvbut8vsw6d7'
    at KA.graph (QueryService.js:40:27)
    at KA.query (QueryService.js:22:25)
    at KA.<anonymous> (QueryService.js:136:37)
    at Generator.next (<anonymous>)
    at l (QueryService.js:5:58)`

And i noticed in the network tab that another query with more data was fetched and if i dont query optional properties it works

**Comment by babyfish-ct** [comment]
Try 0.3.7 please

At my timezone, now is too late, so I quickly fix it without validation.

If OK, that's good, otherwise, I will fix it next day

**Comment by robsonfj** [comment]
Working great here so far, now it works with optional scalars too.

Thanks 👍
